server:
  port: 7777
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: purchase-service
            uri: https://purchase-service-specialitystore.up.railway.app
            predicates:
              - Path=/purchase/**
          - id: auth-service
            uri: https://specialitystorebackend.up.railway.app
            predicates:
              - Path=/auth/**
